a/urls.py
from django.urls import path
from . import views
app_name = 'a'

urlpatterns = [
    path("", views.index, name="index"),
    path("post/", views.post, name="post"),
    path("contact/", views.contact, name="contact"),
    path('tweet/<int:tweet_id>/delete/', views.delete_tweet, name='delete_tweet'), 
    path('edit/<int:tweet_id>/', views.edit_tweet, name='edit_tweet'),
]

reitter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('a.urls')),
]

a/models.py
from django.db import models

class Tweet(models.Model):
    message = models.CharField(max_length=40)
    name = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True) 

a/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Tweet
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404

def index(request):
    tweet_list = Tweet.objects.all()
    return render(
        request,
        'index.html',
        {'tweet_list': tweet_list}
    )

def post(request):
    message = request.POST['message']
    name = request.POST['name']
    tweet = Tweet(message=message, name=name)
    tweet.save()
    return HttpResponseRedirect(reverse('a:index'))

def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        emailMessage = EmailMessage(
            to=['fko2347041@stu.o-hara.ac.jp'],
            subject='お問い合わせがありました：{0}'.format(subject),
            body='名前: {0}\nメールアドレス: {1}\n本文: {2}'.format(name, email, message),
        )
        emailMessage.send()
        return HttpResponseRedirect('/contact')
    else:
        return render(request, 'contact.html')
    
def delete_tweet(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)
    tweet.delete()
    return HttpResponseRedirect(reverse('a:index'))

def edit_tweet(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)

    if request.method == 'POST':
        tweet.message = request.POST['message']
        tweet.name = request.POST['name']
        tweet.save()
        return redirect('a:index')

    return render(request, 'edit_tweet.html', {'tweet': tweet})

a/templates/contact.html
<style>
  a {
    text-decoration: none;
  }
</style>

{% load static %}
<!DOCTYPE html>
<html lang="ja">
<link href="{% static 'css/style.css' %}" rel="stylesheet"> 
<link href="{% static 'images/reitter_l.ico' %}" rel="icon"> 
<title>reitter:お問い合わせ</title>

<body>
<h1>
  <a href="../../"><div style="text-align: center"><p style="background-color:#00FFFF"><font color = "white"><big>・・・Reitter🕊・・・</big></font></p></div></a>
</h1>

<a href ="../">retter:トップ</a> > お問い合わせ

<p class="otoiawase">お問い合わせ</p>

<form method="post">
  {% csrf_token %}
  <body>
    <div>
      <label for="name"><big>　  名 　　前 　:</big></label>
      <input type="text" name="name" id="name" />
    </div>
    <br>
    <div>
      <label for="email"><big>メールアドレス:</big></label>
      <input type="email" name="email" id="email" />
    </div>
    <br>
    <div>
      <label for="subject"><big>　  要 　　件 　:</big></label>
      <input type="text" name="subject" id="subject" />
    </div>
    <br>
    <button type="submit" class="sousin"><big>送信</big></button>
  </body>
</form>
<h2>
  <div style="text-align: center"><p style="background-color:#00FFFF"><font color = "white">2024@reitter:contact</font></p></div>
</h2>
</body>

a/templates/edit_tweet.html
<style>
  a {
    text-decoration: none;
  }
</style>

{% load static %}
<!DOCTYPE html>
<html lang="ja">
<link href="{% static 'css/style.css' %}" rel="stylesheet"> 
<link href="{% static 'images/reitter_l.ico' %}" rel="icon"> 
<title>reitter:編集</title>

<body>
<h1>
  <a href="../../"><div style="text-align: center"><p style="background-color:#00FFFF"><font color = "white"><big>・・・Reitter🕊・・・</big></font></p></div></a>
</h1>
<a href ="../../">retter:トップ</a> > ✂編集

<p class="komentoran">✂編集</p>
  <form method="post">
    {% csrf_token %}
    <p><big>[{{ tweet.created_at|date:'H:i'}}]のコメント</big></p>
    <div>
      <label for="name"><big>　名　前　:</big></label>
      <input type="text" name="name" value="{{ tweet.name }}">
    </div>
    <br>
    <div>
      <label for="message"><big>メッセージ:</big></label>
      <input type="text" name="message" value="{{ tweet.message }}">
    </div>
    <br>
    <input type="submit" class ="sousin">
  </form>
  <h2>
    <div style="text-align: center"><p style="background-color:#00FFFF"><font color = "white">2024@reitter:edit</font></p></div>
  </h2>
</body>

a/templates/index.html
<style>
  .button {
    display: inline-block;
    padding: 0.3em 1em;
    text-decoration: none;
    color: #ff4500;
    border: solid 2px #ff4500;
    border-radius: 3px;
    transition: .4s;
  }

  .button:hover {
    background: #ff4500;
    color: white;
  }

  a {
    text-decoration: none;
    color:blue;
  }
</style>

{% load static %}
<!DOCTYPE html>
<html lang="ja">
<link href="{% static 'css/style.css' %}" rel="stylesheet"> 
<link href="{% static 'images/reitter_l.ico' %}" rel="icon"> 
<title>reitter:トップ</title>

<body>
<h1>
  <a href="#"><div style="text-align: center"><p style="background-color:#00FFFF"><font color = "white"><big>・・・Reitter🕊・・・</big></font></p></div></a>
</h1>

<div class="center">
  <p class="komentoran">🖊みんなのコメント</p>
  {% for tweet in tweet_list %}
  <div class="box"><p><big>
    [{{ tweet.created_at|date:'H:i'}}]
    {{tweet.name}}さん:
    {{tweet.message}} 
    </big>
    <a href="{% url 'a:edit_tweet' tweet.id %}" class="sousin">編集</a>
    <a href="{% url 'a:delete_tweet' tweet.id %}" class="button">削除</a>
  </p></div>
  {% endfor %}
</div>

<h2></h2>

<p class="komentoran">✉投稿✉</p>
<form action="post/" method="POST">
  {% csrf_token %}
  <div>
    <label for="name"><big>　名　前　:</big></label>
    <input type="text" name="name" />
  </div>
  <br>
  <div>
    <label for="message"><big>メッセージ:</big></label>
    <input type="text" name="message" />
  </div>
  <br>

  <input type="submit" class="sousin">
</form>
  <p style="text-align: right">✉お問い合わせは👉<a href="contact">こちら</a>から</p>
<h2>
  <div style="text-align: center"><p style="background-color:#00FFFF"><font color = "white">2024@reitter:top</font></p></div>
</h2>
</body>
</html>